Projeto.NAC.Fiap/Models/Venda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projeto.NAC.Fiap.Models
{
    public class Venda
    {
        [Key]
        public int VendaId { get; set; }
        public string Cliente { get; set; }
        public DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public bool Pago { get; set; }
    }
}

Projeto.NAC.Fiap/Controllers/VendaController.cs
using Projeto.NAC.Fiap.Models;
using Projeto.NAC.Fiap.Unity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto.NAC.Fiap.Controllers
{
    public class VendaController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpPost]
        public ActionResult Pagar(int codigo)
        {
            var venda = _unit.VendaRepository.BuscarPor(v => v.VendaId == codigo)[0];
            venda.Pago = true;
            _unit.VendaRepository.Atualizar(venda);
            _unit.Salvar();
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Buscar(bool pago)
        {
            var lista = _unit.VendaRepository.BuscarPor(v => v.Pago == pago);
            return View("Listar", lista);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_unit.VendaRepository.Listar());
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Venda venda)
        {
            _unit.VendaRepository.Cadastrar(venda);
            _unit.Salvar();
            TempData["msg"] = "Cadastrardo";
            return RedirectToAction("Cadastrar");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Projeto.NAC.Fiap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Projeto.NAC.Fiap/Views/Venda/Cadastrar.cshtml
@model Projeto.NAC.Fiap.Models.Venda
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(v => v.Cliente)
        @Html.TextBoxFor(v => v.Cliente, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(v => v.Data)
        @Html.TextBoxFor(v => v.Data, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(v => v.Valor)
        @Html.TextBoxFor(v => v.Valor, new { @class = "form-control" })
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Projeto.NAC.Fiap/Views/Venda/Listar.cshtml
@model List<Projeto.NAC.Fiap.Models.Venda>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

@using (Html.BeginForm("Buscar", "Venda", FormMethod.Get))
{
    @Html.CheckBox("Pago")
    @Html.Label("Pago")
    <input type="submit" value="Buscar" class="btn btn-primary" />
}

<table class="table table-striped">
    <tr>
        <th>Cliente</th>
        <th>Data</th>
        <th>Valor</th>
        <th>Pago</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Cliente</td>
            <td>@item.Data.ToShortDateString()</td>
            <td>@item.Valor</td>
            <td>@(item.Pago? "Sim":"Não")</td>
            <td>
                <!-- Button trigger modal -->
                <button @(item.Pago?"disabled": "") onclick="codigo.value = @item.VendaId" type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
                    Pagar
                </button>
            </td>
        </tr>
    }
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Tem certeza disso
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Pagar", "Venda"))
                {
                    <input type="hidden" id="codigo" name="codigo"
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                }
            </div>
        </div>
    </div>
</div>